dist: xenial   # required for Python >= 3.7
language: python
python: "3.7"
git:
  depth: false
before_install:
  - pip install poetry
install:
  # we run `poetry version` here to appease poetry about '0.0.0-source'
  - poetry version
  - poetry install
script:
  - poetry run python --version
  - poetry run behave
before_deploy:
  - poetry config http-basic.pypi $PYPI_USER $PYPI_PASS
  - poetry version $TRAVIS_TAG
  - poetry build
deploy:
  - provider: script
    script: echo "fake deploy"
    skip_cleanup: true
    on:
      branch: master
      tags: true
after_deploy:
  - git config --global user.email "jrnl.bot@gmail.com"
  - git config --global user.name "Jrnl Bot"
  - git checkout master
  - git add pyproject.toml
  - git commit -m "Incrementing version to ${TRAVIS_TAG}"
  - git push https://${GITHUB_TOKEN}@github.com/jrnl-org/jrnl.git master
